### Send new version of deployed service
POST localhost:8080/deploy
Content-Type: application/json

{
  "name": "Service B",
  "version": 3
}

### Get list of services by System version
GET localhost:8080/services?systemVersion=5